go:
  version: 1.17
repository:
  path: github.com/observatorium/obsctl
build:
  binaries:
    - name: obsctl
      path: ./
  flags: -a -tags netgo
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
    - linux/arm64
    - windows/amd64
    - freebsd/amd64
    - linux/ppc64le
