version: 2.1

orbs:
  go: circleci/go@1.7.1

executors:
  golang:
    docker:
      - image: cimg/go:1.17-node

jobs:
  # Cross build is needed for publish_release but needs to be done outside of docker.
  cross_build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/observatorium/obsctl
    environment:
      GOBIN: "/home/circleci/.go_workspace/go/bin"
      PROMU_VERSION: "0.5.0"
    steps:
      - checkout
      - run: mkdir -p ${GOBIN}
      - run: curl -L "https://github.com/prometheus/promu/releases/download/v${PROMU_VERSION}/promu-${PROMU_VERSION}.$(go env GOOS)-$(go env GOARCH).tar.gz" | tar --strip-components=1 -xzf - -C ${GOBIN}
      - run: mv -f ${GOBIN}/promu "${GOBIN}/promu-v${PROMU_VERSION}"
      - run: make crossbuild -W ${GOBIN}/promu-v${PROMU_VERSION} # Ignore make dependency, it needs to be enforced somehow.
      - persist_to_workspace:
          root: .
          paths:
            - .build

  publish_release:
    executor: golang
    steps:
      - checkout
      - go/mod-download-cached
      - setup_remote_docker:
          version: 20.10.12
      - attach_workspace:
          at: .
      - run: make tarballs-release
      - store_artifacts:
          path: .tarballs
          destination: releases

# Only run on tags
workflows:
  version: 2
  obsctl:
    jobs:
      - cross_build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
      - publish_release:
          requires:
            - cross_build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
